### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by johannes-z** [johannes-z/dnd-yml2svg#1]
- [ ] Better support for different kind of traps
- [ ] Don't assume that `connection.via` is a door (or something similar) 
- [x] Output (link) all generated `.svg` files into a `.html` file
  - [x] Browser sync the `.html` file
- [ ] Add additional infos for rooms (nodes)
  - [ ] Treasure parcels
  - [ ] Encounter details
  - [ ] Environment (e.g. hazards)
